### ISSUE TITLE
dockerfile java error

### ISSUE THREAD

**Issue by spyroslalos** [muuki88/activator-akka-docker#1]
Hello, 

i have this problem when runnning:

```
$ sbt docker:publishLocal

[info] Step 0 : FROM dockerfile/java
[info] Pulling repository docker.io/dockerfile/java
[error] Error: image dockerfile/java:latest not found
java.lang.RuntimeException: Nonzero exit value: 1
    at com.typesafe.sbt.packager.docker.DockerPlugin$class.publishLocalDocker(DockerPlugin.scala:105)
    at com.typesafe.sbt.SbtNativePackager$.publishLocalDocker(PackagerPlugin.scala:11)
    at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$dockerSettings$14.apply(DockerPlugin.scala:178)
    at com.typesafe.sbt.packager.docker.DockerPlugin$$anonfun$dockerSettings$14.apply(DockerPlugin.scala:177)
    at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:35)
    at scala.Function4$$anonfun$tupled$1.apply(Function4.scala:34)
    at scala.Function1$$anonfun$compose$1.apply(Function1.scala:47)
    at sbt.$tilde$greater$$anonfun$$u2219$1.apply(TypeFunctions.scala:42)
    at sbt.std.Transform$$anon$4.work(System.scala:64)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:237)
    at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
    at sbt.Execute.work(Execute.scala:244)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:237)
    at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:160)
    at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
    at java.util.concurrent.FutureTask.run(FutureTask.java:262)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:745)
```

any ideas?

**Comment by muuki88** [comment]
thanks for reporting. The `dockerBaseImage` is not available anymore. The `dockerfile` repos have been discontinued. Upgrading the `sbt-native-packager` solved the issue.

**Comment by wir33658** [comment]
Hi, just pulled the master, but still getting

C:\Users\rtweissm\Development\MID\Playground\activator-akka-docker>sbt
[info] Loading project definition from C:\Users\rtweissm\Development\MID\Playground\activator-akka-docker\project
[info] Set current project to akka-docker (in build file:/C:/Users/rtweissm/Development/MID/Playground/activator-akka-docker/)

> clean
> [success] Total time: 0 s, completed 31.08.2015 16:02:58
> compile
> [info] Updating {file:/C:/Users/rtweissm/Development/MID/Playground/activator-akka-docker/}activator-akka-docker...
> [info] Resolving jline#jline;2.12 ...
> [info] Done updating.
> [info] Compiling 4 Scala sources to C:\Users\rtweissm\Development\MID\Playground\activator-akka-docker\target\scala-2.11\classes...
> [warn] there were two feature warnings; re-run with -feature for details
> [warn] one warning found
> [success] Total time: 7 s, completed 31.08.2015 16:03:09
> docker:publishLocal
> [info] Packaging C:\Users\rtweissm\Development\MID\Playground\activator-akka-docker\target\scala-2.11\akka-docker_2.11-2.3.10-sources.jar ...
> [info] Done packaging.
> [info] Wrote C:\Users\rtweissm\Development\MID\Playground\activator-akka-docker\target\scala-2.11\akka-docker_2.11-2.3.10.pom
> [info] Main Scala API documentation to C:\Users\rtweissm\Development\MID\Playground\activator-akka-docker\target\scala-2.11\api...
> [info] Packaging C:\Users\rtweissm\Development\MID\Playground\activator-akka-docker\target\scala-2.11\akka-docker_2.11-2.3.10.jar ...
> [info] Done packaging.
> [warn] there were two feature warnings; re-run with -feature for details
> model contains 8 documentable templates
> [warn] C:\Users\rtweissm\Development\MID\Playground\activator-akka-docker\src\main\scala\com\example\NodeConfig.scala:63: Tag '@throw' is not recognised
> [warn]   /**
> [warn]   ^
> [warn] two warnings found
> [info] Main Scala API documentation successful.
> [info] Packaging C:\Users\rtweissm\Development\MID\Playground\activator-akka-docker\target\scala-2.11\akka-docker_2.11-2.3.10-javadoc.jar ...
> [info] Done packaging.
> [error] Post http://127.0.0.1:2375/v1.20/build?cgroupparent=&cpuperiod=0&cpuquota=0&cpusetcpus=&cpusetmems=&cpushares=0&dockerfile=Dockerfile&forcerm=1&memory=0&memswap=0&rm=1&t=akka-docker%3A2.3.10&ulimit
> [error] \* Are you trying to connect to a TLS-enabled daemon without TLS?
> [error] \* Is your docker daemon up and running?
> [trace] Stack trace suppressed: run last docker:publishLocal for the full output.
> [error](docker:publishLocal) Nonzero exit value: 1
> [error] Total time: 5 s, completed 31.08.2015 16:03:31

**Comment by muuki88** [comment]
You need to have `docker` docker installed locally and available in your environment. I'm not sure how this works on windows. SBT Native Packager just forks a process and calls `docker <args>`
